### ISSUE TITLE
Where the **** are the stars?

### ISSUE THREAD

**Issue by Anachron** [jakiestfu/himawari.js#12]
On a high resolution image should be at least a single star visible? These look fake:
https://github.com/jakiestfu/himawari.js#example-images

**Comment by n0um3n4** [comment]
Maybe,
[Olbers' Paradox](http://hyperphysics.phy-astr.gsu.edu/hbase/astro/olbers.html)

> Were the succession of stars endless, then the background of the sky would present us a uniform luminosity, like that displayed by the Galaxy–since there could be absolutely no point, in all that background, at which would not exist a star. The only mode, therefore, in which, under such a state of affairs, we could comprehend the voids which our telescopes find in innumerable directions, would be by supposing that the distance o the invisible background [is] so immense that no ray from it has yet been able to reach us at all - E.A.P

Or [maybe](http://www.physlink.com/Education/AskExperts/ae323.cfm)

**Comment by jakiestfu** [comment]
Himawari 8 is a weather satellite. It is naive to think the highly tuned cameras on this satellite work like any regular camera.
