### ISSUE TITLE
unhandled ETIMEDOUT stream error

### ISSUE THREAD

**Issue by ungoldman** [jakiestfu/himawari.js#5]
See https://github.com/ngoldman/himawari-bg/issues/5 for the original error

```
$ node ngoldman-himawari-bg-example.js
Downloading satellite images [==                  ] 12% 797.2sstream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: ETIMEDOUT
    at null._onTimeout (/Users/Kiven/node_modules/himawari-bg/node_modules/himawari/node_modules/request/request.js:762:15)
    at Timer.listOnTimeout (timers.js:92:15)
```

Might be handle-able by `request`'s timeout option: https://github.com/request/request#timeouts

Looks like you already have a timeout set at https://github.com/jakiestfu/himawari.js/blob/master/index.js#L143 but I think you may need to add a `.on('error')` handler to the `request` call before piping to `stream`.

**Comment by jakiestfu** [comment]
I've been trying to pinpoint this error. So terror handler for the file stream wouldn't catch the request error? Makes perfect sense. This in addition with the async retry logic would make downloads virtually bulletproof. Will add and test this soon, thanks for the insight!

**Comment by jakiestfu** [comment]
Fixed https://github.com/jakiestfu/himawari.js/commit/9f774d79cc8647f4dd074f1fc94369f1d9feb391#diff-168726dbe96b3ce427e7fedce31bb0bc
